#!/bin/bash
#SBATCH --partition=htc
#SBATCH --cluster=htc
#SBATCH --job-name=Functator
#SBATCH --time=10:00:00
#SBATCH --output=output/Functator_db_%A_%a.out
#SBATCH --error=output/Functator_db_%A_%a.err  ###with jobID (%A) and elementID (%a) variables 
#SBATCH --nodes=1
#SBATCH --cpus-per-task=10 # RequesGt that ncpus be allocated per process.
#SBATCH --mem=38GB
######SBATCH --array=0-10

module load  gatk/4.5.0.0

Filenames=($(cat input/samples.5cols.txt | cut -f4))


sample=${Filenames[${SLURM_ARRAY_TASK_ID}]}

echo $sample


#To call mutations on a tumor sample, call in this mode using a PoN and germline resource.
#https://gatk.broadinstitute.org/hc/en-us/articles/360037593851-Mutect2
#/software/rhel9/spack/install/linux-rhel9-x86_64/gcc-11.4.1/gatk-4.5.0.0-sl3qs3nlbwenhg3tjopzcj7oufvwgjaa/bin/gatk Mutect2 -R input/Homo_sapiens_assembly38.fasta -I output/${sample}.BQSR.sorted.bam -L input/A3416642_Covered.bed --germline-resource input/af-only-gnomad.hg38.vcf.gz --panel-of-normals input/1000g_pon.hg38.vcf.gz -O output/${sample}_somatic_variants_mutect2.vcf.gz --f1r2-tar-gz output/${sample}_f1r2.tar.gz


# Run GetPileupSummaries to summarize read support for a set number of known variant sites.
#https://gatk.broadinstitute.org/hc/en-us/articles/360035531132--How-to-Call-somatic-mutations-using-GATK4-Mutect2
#/software/rhel9/spack/install/linux-rhel9-x86_64/gcc-11.4.1/gatk-4.5.0.0-sl3qs3nlbwenhg3tjopzcj7oufvwgjaa/bin/gatk GetPileupSummaries --java-options '-Xmx50G' -I output/${sample}.BQSR.sorted.bam -V input/af-only-gnomad.hg38.vcf.gz -L input/A3416642_Covered.bed -O output/${sample}_getpileupsummaries.table

# Calculate tumor-only contamination calculation.
#https://gatk.broadinstitute.org/hc/en-us/articles/360035531132--How-to-Call-somatic-mutations-using-GATK4-Mutect2
#/software/rhel9/spack/install/linux-rhel9-x86_64/gcc-11.4.1/gatk-4.5.0.0-sl3qs3nlbwenhg3tjopzcj7oufvwgjaa/bin/gatk --java-options "-Xmx50G" CalculateContamination -I output/${sample}_getpileupsummaries.table -O output/${sample}_contamination.table

# read orientation
#/software/rhel9/spack/install/linux-rhel9-x86_64/gcc-11.4.1/gatk-4.5.0.0-sl3qs3nlbwenhg3tjopzcj7oufvwgjaa/bin/gatk LearnReadOrientationModel -I output/${sample}_f1r2.tar.gz -O output/${sample}_read-orientation-model.tar.gz

#Filter Variants Called By Mutect2
#/software/rhel9/spack/install/linux-rhel9-x86_64/gcc-11.4.1/gatk-4.5.0.0-sl3qs3nlbwenhg3tjopzcj7oufvwgjaa/bin/gatk FilterMutectCalls -V output/${sample}_somatic_variants_mutect2.vcf.gz -R input/Homo_sapiens_assembly38.fasta --contamination-table output/${sample}_contamination.table --ob-priors output/${sample}_read-orientation-model.tar.gz -O output/${sample}_somatic_variants_filtered_mutect2.vcf

# annotate variants
# download databases to annotate variants this doesnt work i use wget  ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/funcotator/funcotator_dataSources.v1.8.hg38.20230908s.tar.gz
#/software/rhel9/spack/install/linux-rhel9-x86_64/gcc-11.4.1/gatk-4.5.0.0-sl3qs3nlbwenhg3tjopzcj7oufvwgjaa/bin/gatk FuncotatorDataSourceDownloader --somatic --validate-integrity --extract-after-download --hg38


#/software/rhel9/spack/install/linux-rhel9-x86_64/gcc-11.4.1/gatk-4.5.0.0-sl3qs3nlbwenhg3tjopzcj7oufvwgjaa/bin/gatk Funcotator --variant output/${sample}_somatic_variants_filtered_mutect2.vcf --reference input/Homo_sapiens_assembly38.fasta --ref-version hg38 --data-sources-path input/funcotator_dataSources.v1.8.hg38.20230908s --output output/${sample}_somatic_variants_functotated.vcf --output-file-format VCF
